### RandomForest
- 집단 학습을 기반으로 고정밀 분류, 회귀, 클러스터링 등을 구현
- 학습 전용 데이터를 기반으로 다수의 의사결정트리를 만들고 만들어진 의사결정 트리를 기반으로 다수결로 결과를 유도하는 모델

In [1]:
import pandas as pd

In [ ]:
iris = pd.read_csv('../Data/iris.csv')
iris.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [11]:
# 이상이 없다면 Feature 와 Target 분리
iris_data = iris[['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth']]
iris_target = iris['Name']

In [18]:
# Data 크기 확인
print(iris_data.shape)
print(iris_target.shape)

(150, 4)
(150,)

# Train 과 Test 분리

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
train_data, test_data, train_target, test_target = \
    train_test_split(
        iris_data,
        iris_target,
        random_state=42,
        stratify=iris_target
    )

In [23]:
print(train_data.shape)
print(test_data.shape)
print(train_target.shape)
print(test_target.shape)

(112, 4)
(38, 4)
(112,)
(38,)

#### RandomForest 로 분류해보기

In [24]:
from sklearn.ensemble import RandomForestClassifier  # Regressor : 주관식

In [25]:
# 모델 만들기
clf = RandomForestClassifier()   # 기본값 : 100

In [26]:
# 학습 시키기
clf.fit(train_data, train_target)

RandomForestClassifier()

In [27]:
# 평가하기
clf.score(test_data, test_target)

0.8947368421052632

-----
#### 독버섯과 관련된 데이터를 사용한 머신러닝
 - 8124 종류의 버섯의 특징과 독의 유무로 구성되어 있는 데이터셋
 - 버섯의 특징을 기반으로 독의 유무를 판단

In [30]:
# 데이터 불러오기 (크롤링)
import urllib.request as req

local = "../Data/mushroom.csv"
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"

req.urlretrieve(url, local)   # url 주소 거를 요청해서 local 에 넣어라
print("OK")

OK

#### 랜덤포레스트를 이용한 버섯 분류

In [31]:
import pandas as pd

In [33]:
mr = pd.read_csv('../Data/mushroom.csv', header=None)
mr.head()   # 찍어봤더니 이상하게 나옴. => header = None

  0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0  p  x  s  n  t  p  f  c  n  k  ...  s  w  w  p  w  o  p  k  s  u
1  e  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
2  e  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
3  p  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
4  e  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g

[5 rows x 23 columns]

In [34]:
mr.shape

(8124, 23)

- 한 줄이 버섯 한 종류
- 첫 번째 열 : p(독버섯), e(식용)
- 두 번째 열 : 버섯의 머리 모양 -> b(종 모양), c(원뿔 모양), x(볼록), f(평평), k(혹), s(오목)
- 네 번째 열 : 버섯의 머리 색깔 -> n(갈색), b(황갈색), c(연한갈색)
##### - Feature Data 가 알파벳 1자리 문자 -> Feature 는 숫자로 변환작업 해야함.

-----
##### 연습

In [40]:
# 알파벳 - ASCII(아스키) 코드
ord('x')

120

In [41]:
# ASCII -> 알파벳
chr(120)

'x'

In [45]:
# mr 의 1번 컬럼을 숫자로 변경. 하나씩 바꾸므로 for 문 사용함.
for i in mr.loc[:,1]:
    print(i, ord(i))

x 120
x 120
b 98
x 120
x 120
x 120
b 98
b 98
x 120
b 98
x 120
x 120
b 98
x 120
x 120
s 115
f 102
x 120
x 120
x 120
b 98
x 120
b 98
b 98
b 98
f 102
x 120
x 120
f 102
x 120
b 98
x 120
x 120
x 120
b 98
x 120
s 115
x 120
x 120
b 98
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
b 98
x 120
x 120
b 98
f 102
b 98
x 120
x 120
s 115
b 98
b 98
b 98
b 98
f 102
x 120
f 102
x 120
x 120
f 102
b 98
f 102
x 120
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
b 98
x 120
f 102
s 115
x 120
b 98
x 120
x 120
x 120
x 120
f 102
x 120
b 98
x 120
x 120
b 98
f 102
x 120
b 98
x 120
x 120
b 98
b 98
x 120
x 120
s 115
x 120
x 120
x 120
x 120
s 115
x 120
x 120
s 115
x 120
x 120
f 102
f 102
x 120
x 120
b 98
f 102
x 120
b 98
b 98
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
b 98
x 120
b 98
s 115
f 102
x 120
x 120
f 102
x 120
b 98
b 98
x 120
x 120
x 120
s 115
x 120
x 120
b 98
x 120
b 98
b 98
b 98
b 98
x 120
f 102
x 120
f 102
b 98
b 98
x 120
b 98
x 120
b 98
x 120
b 98
f 102
b 98
b 98
b 98
x 120
b 98
x 120
s 115
f 102
x 120
f 102
x 120
b 98
f 102
b 98
x 120
x 120
x 120
b 98
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
b 98
x 120
x 120
f 102
x 120
b 98
b 98
b 98
b 98
x 120
b 98
x 120
x 120
f 102
b 98
x 120
x 120
x 120
s 115
x 120
x 120
x 120
f 102
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
x 120
f 102
b 98
x 120
x 120
b 98
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
s 115
b 98
b 98
b 98
f 102
x 120
b 98
b 98
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
b 98
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
b 98
s 115
x 120
b 98
f 102
b 98
b 98
x 120
f 102
x 120
b 98
x 120
b 98
x 120
b 98
x 120
x 120
f 102
x 120
x 120
b 98
x 120
b 98
x 120
x 120
b 98
x 120
f 102
x 120
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
b 98
x 120
b 98
x 120
x 120
b 98
b 98
x 120
b 98
b 98
b 98
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
f 102
b 98
x 120
x 120
x 120
f 102
x 120
f 102
f 102
b 98
b 98
x 120
s 115
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
b 98
x 120
x 120
f 102
x 120
s 115
x 120
b 98
s 115
b 98
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
x 120
x 120
b 98
x 120
b 98
x 120
b 98
x 120
f 102
x 120
x 120
x 120
x 120
x 120
b 98
b 98
x 120
b 98
x 120
x 120
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
f 102
x 120
b 98
x 120
f 102
x 120
x 120
f 102
b 98
x 120
f 102
x 120
x 120
b 98
b 98
f 102
b 98
x 120
x 120
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
b 98
x 120
x 120
b 98
b 98
x 120
b 98
x 120
b 98
b 98
f 102
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
b 98
f 102
x 120
x 120
f 102
s 115
f 102
f 102
x 120
b 98
x 120
b 98
b 98
b 98
f 102
f 102
f 102
f 102
x 120
s 115
x 120
x 120
f 102
f 102
x 120
f 102
x 120
b 98
f 102
f 102
x 120
b 98
x 120
b 98
x 120
b 98
b 98
x 120
x 120
f 102
x 120
f 102
f 102
b 98
x 120
s 115
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
f 102
x 120
f 102
b 98
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
b 98
s 115
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
b 98
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
f 102
x 120
b 98
x 120
f 102
x 120
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
s 115
f 102
s 115
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
b 98
x 120
x 120
x 120
x 120
f 102
f 102
b 98
b 98
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
b 98
f 102
b 98
b 98
s 115
f 102
b 98
x 120
f 102
f 102
x 120
f 102
s 115
b 98
b 98
f 102
b 98
x 120
x 120
x 120
b 98
f 102
x 120
x 120
x 120
b 98
x 120
f 102
f 102
f 102
x 120
b 98
b 98
x 120
f 102
x 120
b 98
f 102
x 120
x 120
x 120
f 102
b 98
x 120
f 102
b 98
x 120
x 120
x 120
b 98
b 98
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
f 102
b 98
x 120
x 120
b 98
b 98
x 120
f 102
x 120
b 98
b 98
x 120
x 120
f 102
x 120
f 102
x 120
b 98
f 102
f 102
b 98
s 115
x 120
b 98
f 102
f 102
x 120
b 98
b 98
b 98
b 98
x 120
x 120
s 115
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
b 98
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
x 120
x 120
b 98
x 120
b 98
f 102
x 120
b 98
b 98
x 120
f 102
x 120
b 98
f 102
b 98
b 98
b 98
f 102
x 120
b 98
x 120
b 98
f 102
x 120
x 120
x 120
f 102
x 120
f 102
b 98
b 98
x 120
b 98
x 120
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
s 115
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
f 102
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
b 98
b 98
f 102
b 98
x 120
b 98
x 120
b 98
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
b 98
x 120
b 98
x 120
x 120
x 120
f 102
f 102
x 120
f 102
s 115
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
b 98
s 115
x 120
x 120
x 120
b 98
b 98
x 120
b 98
f 102
s 115
x 120
s 115
f 102
f 102
b 98
b 98
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
b 98
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
b 98
x 120
x 120
b 98
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
b 98
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
b 98
x 120
x 120
x 120
f 102
f 102
f 102
b 98
f 102
f 102
x 120
b 98
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
b 98
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
b 98
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
b 98
b 98
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
b 98
f 102
b 98
f 102
b 98
x 120
f 102
x 120
s 115
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
b 98
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
b 98
x 120
f 102
f 102
f 102
b 98
x 120
x 120
x 120
x 120
b 98
x 120
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
x 120
b 98
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
b 98
x 120
x 120
b 98
x 120
b 98
x 120
x 120
b 98
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
b 98
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
b 98
f 102
f 102
x 120
b 98
x 120
f 102
x 120
f 102
f 102
x 120
f 102
b 98
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
x 120
x 120
b 98
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
b 98
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
f 102
b 98
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
b 98
f 102
f 102
f 102
f 102
x 120
b 98
f 102
f 102
x 120
f 102
x 120
x 120
b 98
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
b 98
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
b 98
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
b 98
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
b 98
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
b 98
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102

In [56]:
data=[]
target = []

for row_index, row in mr.iterrows():        # iterrows : 한 줄씩 데이터 지정하는 거
    #print(row_index, ":", row)
    #print(row.loc[0])
    #print(row.loc[1])
    #print('----')
    target.append(row.loc[0])
    row_data = []        # [[], []] 식의 2차원 배열이기 때문에 data 안에 또 들어갈 row_data 를 만들어 줌
    for v in row.loc[1:]:
        row_data.append(ord(v))
    data.append(row_data)

In [58]:
print(data[:2])
print(target[:2])

[[120, 115, 110, 116, 112, 102, 99, 110, 107, 101, 101, 115, 115, 119, 119, 112, 119, 111, 112, 107, 115, 117], [120, 115, 121, 116, 97, 102, 99, 98, 107, 101, 99, 115, 115, 119, 119, 112, 119, 111, 112, 110, 110, 103]]
['p', 'e']

#### DataFrame 만들기

In [59]:
# Target 을 기준으로 DataFrame 만들기
targetTemp = pd.DataFrame(target)
targetTemp.head()

   0
0  p
1  e
2  e
3  p
4  e

In [62]:
# data 를 DataFrame 으로 만들고 column 이름을 겹치지 않게 하기
dataTemp = pd.DataFrame(data)
dataTemp.rename(columns=lambda x: x+1, inplace=True)    # 람다함수 : 함수 이름이 없고 return 이 없음. 컬럼 번호를 +1 하게 함
dataTemp.head()

,1,2,3,4,5,6,7,8,9,10,...,13,14,15,16,17,18,19,20,21,22
0,120,115,110,116,112,102,99,110,107,101,...,115,119,119,112,119,111,112,107,115,117
1,120,115,121,116,97,102,99,98,107,101,...,115,119,119,112,119,111,112,110,110,103
2,98,115,119,116,108,102,99,98,110,101,...,115,119,119,112,119,111,112,110,110,109
3,120,121,119,116,112,102,99,110,110,101,...,115,119,119,112,119,111,112,107,115,117
4,120,115,103,102,110,102,119,98,107,116,...,115,119,119,112,119,111,101,110,97,103

In [63]:
# 2개의 dataframe 을 합치기
mr2 = pd.concat([targetTemp, dataTemp], axis='columns')   # columns 방향으로 합치기.
mr2.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,p,120,115,110,116,112,102,99,110,107,...,115,119,119,112,119,111,112,107,115,117
1,e,120,115,121,116,97,102,99,98,107,...,115,119,119,112,119,111,112,110,110,103
2,e,98,115,119,116,108,102,99,98,110,...,115,119,119,112,119,111,112,110,110,109
3,p,120,121,119,116,112,102,99,110,110,...,115,119,119,112,119,111,112,107,115,117
4,e,120,115,103,102,110,102,119,98,107,...,115,119,119,112,119,111,101,110,97,103

In [64]:
mr2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       8124 non-null   object
 1   1       8124 non-null   int64
 2   2       8124 non-null   int64
 3   3       8124 non-null   int64
 4   4       8124 non-null   int64
 5   5       8124 non-null   int64
 6   6       8124 non-null   int64
 7   7       8124 non-null   int64
 8   8       8124 non-null   int64
 9   9       8124 non-null   int64
 10  10      8124 non-null   int64
 11  11      8124 non-null   int64
 12  12      8124 non-null   int64
 13  13      8124 non-null   int64
 14  14      8124 non-null   int64
 15  15      8124 non-null   int64
 16  16      8124 non-null   int64
 17  17      8124 non-null   int64
 18  18      8124 non-null   int64
 19  19      8124 non-null   int64
 20  20      8124 non-null   int64
 21  21      8124 non-null   int64
 22  22      8124 non-null   int64
dtypes: int64(22), object(1)
memory usage: 1.4+ MB

#### RandomForest 로 분류하기

In [ ]:
mr2_data = mr2.loc[:, 1:]
mr2_data.head()

,1,2,3,4,5,6,7,8,9,10,...,13,14,15,16,17,18,19,20,21,22
0,120,115,110,116,112,102,99,110,107,101,...,115,119,119,112,119,111,112,107,115,117
1,120,115,121,116,97,102,99,98,107,101,...,115,119,119,112,119,111,112,110,110,103
2,98,115,119,116,108,102,99,98,110,101,...,115,119,119,112,119,111,112,110,110,109
3,120,121,119,116,112,102,99,110,110,101,...,115,119,119,112,119,111,112,107,115,117
4,120,115,103,102,110,102,119,98,107,116,...,115,119,119,112,119,111,101,110,97,103

In [ ]:
mr2_target = mr2.loc[:,0]
mr2_target

0       p
1       e
2       e
3       p
4       e
       ..
8119    e
8120    e
8121    e
8122    p
8123    e
Name: 0, Length: 8124, dtype: object

In [75]:
train_data_mr2, test_data_mr2, train_target_mr2, test_target_mr2 = \
    train_test_split(
        mr2_data,
        mr2_target,
        random_state=42,
        stratify=mr2_target
    )

In [77]:
print(train_data_mr2.shape)
print(test_data_mr2.shape)
print(train_target_mr2.shape)
print(test_target_mr2.shape)

(6093, 22)
(2031, 22)
(6093,)
(2031,)

In [78]:
clf.fit(train_data_mr2, train_target_mr2)

RandomForestClassifier()

In [85]:
print(clf.score(train_data_mr2, train_target_mr2))
print(clf.score(test_data_mr2, test_target_mr2))

1.0
1.0

---- 
#### One-hot Encoding
 - 숫자 데이터가 숫자로써 의미가 있으면 상관없지만, 위의 데이터는 알파벳으로 분류(빨강, 갈색)를 위한 데이터이므로 숫자 크기의 의미가 없다.
 - 이때 사용하는 것이 One-hot Encoding 이다.

##### 연습

In [88]:
# 1번 열
dataTemp[1].unique()

array([120,  98, 115, 102, 107,  99])

In [91]:
pd.get_dummies(
    data=dataTemp,
    columns=[1],
    prefix='1'   # 앞에 1이라고 적어줘라
)              # 1_??? 는 True 가 하나고, False 가 나머지이므로 이 행렬을 희소행렬이라 함.

,2,3,4,5,6,7,8,9,10,11,...,19,20,21,22,1_98,1_99,1_102,1_107,1_115,1_120
0,115,110,116,112,102,99,110,107,101,101,...,112,107,115,117,False,False,False,False,False,True
1,115,121,116,97,102,99,98,107,101,99,...,112,110,110,103,False,False,False,False,False,True
2,115,119,116,108,102,99,98,110,101,99,...,112,110,110,109,True,False,False,False,False,False
3,121,119,116,112,102,99,110,110,101,101,...,112,107,115,117,False,False,False,False,False,True
4,115,103,102,110,102,119,98,107,116,101,...,101,110,97,103,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,115,110,102,110,97,99,98,121,101,63,...,112,98,99,108,False,False,False,True,False,False
8120,115,110,102,110,97,99,98,121,101,63,...,112,98,118,108,False,False,False,False,False,True
8121,115,110,102,110,97,99,98,110,101,63,...,112,98,99,108,False,False,True,False,False,False
8122,121,110,102,121,102,99,110,98,116,63,...,101,119,118,108,False,False,False,True,False,False
8123,115,110,102,110,97,99,98,121,101,63,...,112,111,99,108,False,False,False,False,False,True

In [111]:
# 이미 만들어져서 에러 뜸
# 적용하기
dataTemp = mr2.copy()

for i in range(1, 23):
    dataTemp = pd.get_dummies(
        data=dataTemp,
        columns=[i],
        prefix=str(i)
    )

In [112]:
# dataFrame 만들기
mr3 = pd.concat(
    [targetTemp, dataTemp],
    axis='columns'
)
mr3.head()

,0,0,1_98,1_99,1_102,1_107,1_115,1_120,2_102,2_103,...,21_115,21_118,21_121,22_100,22_103,22_108,22_109,22_112,22_117,22_119
0,p,p,False,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,False,True,False
1,e,e,False,False,False,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,False
2,e,e,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,p,p,False,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,False,True,False
4,e,e,False,False,False,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,False

In [113]:
mr3.shape

(8124, 119)

In [115]:
# 이제 띄워보시오 (실습)